spring.application.name=task-management-api
server.port=8081

# Active Profile (dev by default)
spring.profiles.active=dev

# Spring Boot Actuator Endpoint Settings
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Operational Application Info Metrics
info.app.name=Task Management API
info.app.description=Spring Boot REST API with Spring Data JPA, Layered Architecture, and Actuator Health Monitoring
info.app.version=1.0.0